// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2rLfq-DcvZ5eBAAFu86seymo2M4jQgIw',
    appId: '1:327637433145:web:2cb9b5337d0b69fd4086e8',
    messagingSenderId: '327637433145',
    projectId: 'istanabuahemye',
    authDomain: 'istanabuahemye.firebaseapp.com',
    storageBucket: 'istanabuahemye.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZZcF9JdFYXcTQ-MKZkHtmmI3XUtxDCcU',
    appId: '1:327637433145:android:d881a6a2afb100d64086e8',
    messagingSenderId: '327637433145',
    projectId: 'istanabuahemye',
    storageBucket: 'istanabuahemye.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE_UG6N7GOGlw8yzNL7pZe_Vr3zBFnaek',
    appId: '1:327637433145:ios:6f95d834c7a581904086e8',
    messagingSenderId: '327637433145',
    projectId: 'istanabuahemye',
    storageBucket: 'istanabuahemye.appspot.com',
    iosClientId: '327637433145-lkhldvm4omcoah8uv74ntgs3sjhcgt51.apps.googleusercontent.com',
    iosBundleId: 'com.example.istanabuahios',
  );
}
